services:
    acme.payment.payum.extension.store_notification:
        class: Acme\PaymentBundle\Payum\Extension\StoreNotificationExtension
        arguments:
            - @doctrine

    acme.payment.payum.action.store_notification:
        class: Acme\PaymentBundle\Payum\Action\StoreNotificationAction
        arguments:
            - @doctrine

    acme.payment.payum.api.factory:
        class: Acme\PaymentBundle\Payum\Api\Factory
        arguments:
            - @service_container

    acme.payment.payum.paypal_express_checkout_api:
        class: Payum\Paypal\ExpressCheckout\Nvp\Api
        factory_service: acme.payment.payum.api.factory
        factory_method: createPaypalExpressCheckoutApi